### ISSUE TITLE
Autosplitter's splitting is acting weird again

### ISSUE THREAD

**Issue by Tiyenti** [Tiyenti/distance.asl#3]
It's been reported that the autosplitter has split at the beginning of maps (like in Brionac's latest LTE run [here](https://youtu.be/HI3hJX3OgTU)), and also it's apparently been splitting at the start of maps when Tribow was using a custom playlist for Minute Assault runs.

Haven't done any debugging on this yet so currently not sure if this is problem with just the code, or if maybe the pointers are fucked again.

**Comment by ero-qt** [comment]
Probably fixed (for good) in f36d15640e38da76a733dc3c3ef9f0ccdf56ed6b.  

Small issue: I was of the assumption that this file is only meant to work with the 3 main game campaigns, which are what I created the settings around. This doesn't seem to be the case however, meaning those settings may need to be reworked.

**Comment by ero-qt** [comment]
Found the current game mode in string form (always in the 3rd position in `G.gameData_.gameData_.stringDictionary_`). Fixed the settings issue in 67b9f5413976c09642232832e4f0ec9f5e1f166a.
This also opens up being able to use
```cs
split
{
	return !old.PlayerFinished && current.PlayerFinished && settings[current.GameMode + " - " + current.LevelName];
}
```
or similar solutions.

**Comment by ero-qt** [comment]
Some talking to the community and some final edits in 7d3a8be8efc8efd7452505f9c1fe29639e444336 and I think we have a good version.  
Once again, I believe it'd be great to add more settings for the other game modes, but that's more on other people, since I don't have all the information.

Final file [here](https://github.com/just-ero/distance.asl/blob/mono-fixes/distance.asl).

**Comment by Tiyenti** [comment]
I appreciate the effort to rewrite this in a way that's more robust and likely far easier to expand upon without having to go looking for pointers, and I think the more in-depth split options are a nice addition. However, fron my prelimiary tests your current version has numerous regressions that break how things worked before, so I can't merge these changes in until these can be resolved:

* The RTA timer starts later than what the current autosplitter does which breaks how real time is tracked. Original autosplitter starts the timer earlier, before the game time starts counting up - this is intended behaviour, as this matches our RTA timing method where you start timing once you select the first map. (The load removal does appear to work fine from preliminary testing, it's just the real time start point that's broken.) I also don't like how this means it takes a few seconds to confirm
if the script is even working, bad for my sanity with how often it's broken in the past lmao
  * You could probably just solve this by going back to the original script's start check of `current.GameState == 0 && old.GameState == 7;` if you're currently on the main menu. The old one had a somewhat annoying issue where this would result in the autosplitter splitting if you quit the game while livesplit was still open, so maybe if you can find a way to fix that, go for that as well, but otherwise this start method should work unless there's something different about the values your script gets compared to the previous pointer paths.
* Resetting on return to main menu might make sense but it breaks categories like All Offial Sprint, White Sprint Sets and Purple Sprint Sets where returning to the main menu is a requirement to transition between level sets. Timer needs to not reset and continue counting through the menu in this case.
  * The original script's method of checking the pause screen confirm dialog's text for a specific string is probably not the *best* solution, ideally we could have some way to detect whether or not a main menu load came from a exiting the map or something, but that's what was used since it was fairly simple to implement and worked well for what it was.
* The split function you had was straight up broken due to a miscapitalising the `GameState` variable name, but after fixing that myself, there's a regression with how restarts are handled - it splits when you restart the level which is not supposed to happen. This change breaks the autosplitter on things like the Catalysm "restart-to-skip-the-cutscene" strat, and also breaks functionality for Challenge mode speedruns, since it'd split every time you died. (Albiet, noone's really done any Challenge runs yet, but I'd like to keep that level of future-proofing in case someone does want to do one.) This is because restarts/DNFs are internally considered finishing the map, so `playerFinished_` ends up being `true` for these; you'd need to check a `finishType_` variable as well to determine the actual cause of finish (`1` for a normal finish, what we want to split on).
  * I attempted to make this closer to the original function myself; I added a `FinishType` variable that points to `PlayerDataBase.finishType_`, and changed the check to `current.FinishType == 1 && old.FinishType != 1`, but this doesn't appear to replicate the original functionality; this value always appears to be `1` unless an abnormal finish happens which makes it useless for actually detecting splits. The previous version of the script pointed to `ModePlayerInfoBase.finishType_` as far as I'm aware which appeared to always be `0` when not finsihed as far as I could tell (unless this very issue indicates that's not the case). You could possibly snag it from the first index of the `List<ModePlayerInfoBase>` at `GameManager.mode_.modePlayerInfos_`, I just haven't tried that myself since I've not looked into your helpers much so idk how you'd handle getting a list/list item.
  * The `PlayerDataBase.finishType_` solution would probably work if you checked *both*
    `PlayerDataBase.finishType_` and `PlayerDataBase.playerFinished_` but I'm admittedly a bit nervous about that considering that I used to do something similar, but that itself ended up
    causing issues with missed splits (see #1 and 88a91198ba74b11239ce9f38a601038f58030375). Maybe won't be an issue with this version though since all the variables are updated at the same time in `Update`?
* The Echoes and Collapse split just straight up doesn't work at all, as far as I could tell, but I haven't yet looked into why.
* This is admittedly more minor but I also dislike how it doesn't appear to work if you open LiveSplit before the game. Since Distance takes a while to load for me I often start LiveSplit before the game - with the previous script this worked fine, but with your current version it doesn't seem to work like this anymore. Kind of annoying, imo.

As an addendum, given that a lot of this isn't directly relavent to this issue in particular, it'd probably be a good idea to create a pull request so this can be discussed further in a more on-topic location.

**Comment by Tiyenti** [comment]
Follow up to my previous comment: I pushed 680bcfc23e8850b798f76b662b6ef79ea3053690 to my own copy of your mono-fixes branch, which fixes some of the issues I had with the last version you posted:

 * Restores the previous version's timer behaviour, starting upon `current.GameState == 0 && old.GameState == 7` if the current scene is the main menu, and freezing game time until after the first loading screen occurs. I didn't test things too much but even with this in place it does seem like this new version of the script doesn't split upon closing the game, so that's cool.
 * I also fixed the `split` action; I fixed the `GameState` var being mistyped as `gameState`, and I also corrected the last case of the `switch` statement, it was always returning `true` if you weren't in adv/lte/nexus. (Evidentally you forgot to update that part after removing the instant-return if finish condition wasn't met). Along with this I also fixed the `GameMode` variable, as it wasn't actually returning the current game mode string.

Along with that I temporarily commented out the `reset` action until a better solution that doesn't break things is implemented.  Splitting on restarts / timer not working if it's opened before the game are still unaddressed. Latter is really annoying but not a dealbreaker, former is critical for correct behaviour and needs to be fixed before merge

---

Edit @ jan 31st, 21:35 UTC:

Since I previously posted this I commited 48df3406beb860d08bb634783594891fe2d65ad2 and cc6963fceff3bbe7f50569624dd6e50b61ddb414 to my branch that, respectively, adds the `finishType_` check to the `split` check, and also restores the previous behaviour of the `reset` action. I think this kinda speaks to how much easier of a solution your helper classes are compared to searching for pointers, heh, since with pointer paths I'd have absolutely zero idea what I was doing and would have to bug someone who knows, but it was relatively simple to make the changes I wanted to make here (even if there's some things I don't know how to access still, like list items or properties).

That fixes all of the major issues, then, so the last thing I need to do is properly test this, in particular I want to see if adding the finishType check will cause issues like the last time I did that, ha.  I'll probably be merging these changes into master soonish providing nothing appears terribly broken. Thanks for your help with this.

**Comment by ero-qt** [comment]
List items can't be accessed using the helper. `List<T>` has an `_item` field, which is of type `T[]`. `System.Array` does not have any fields. It is known however that arrays have a `Length` property (do not be confused, `List<T>` has a separate `_size` field which should be used for them) at `PointerSize * 3` ( `PointerSize` is `0x4` on 32-bit, `0x8` on 64-bit) and their first item at `PointerSize * 4`. All subsequent items' offsets depend on the size of the type; classes and strings have the `PointerSize`, the numeric types are as large as their bit-size (`sbyte`, `byte`, `bool` are 1 byte, `short`, `ushort` are 2 bytes, etc.). Structs must be evaluated on a case-by-case basis.
